import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#000000' },

  homeContent: { padding: 20, paddingBottom: 40 },
  startBox: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    padding: 20,
    marginBottom: 28,
  },
  startDate: { color: '#8E8E93', fontSize: 14, marginTop: 4 },
  startBtnText: { color: '#000000', fontSize: 16, fontWeight: '700' },
  startBtnBig: { backgroundColor: '#30D158', borderRadius: 16, paddingVertical: 18, alignItems: 'center', marginBottom: 28 },

  historySubDate: { color: '#8E8E93', fontSize: 12, marginBottom: 4 },
  detailTitleInput: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    paddingVertical: 6,
    marginBottom: 4,
  },
  detailGym: { color: '#8E8E93', fontSize: 14, marginBottom: 8 },
  detailNoteInput: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
    minHeight: 44,
    marginBottom: 16,
  },
  sessionTitleInput: { color: '#FFFFFF', fontSize: 18, fontWeight: '700', paddingVertical: 2 },
  gymChip: { alignSelf: 'flex-start', backgroundColor: '#2C2C2E', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 7, marginBottom: 8 },
  gymChipText: { color: '#FFFFFF', fontSize: 13, fontWeight: '600' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 18 },
  metaRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  metaChip: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 9 },
  metaChipOn: { backgroundColor: '#14331F', borderWidth: 1, borderColor: '#30D158' },
  metaChipText: { color: '#FFFFFF', fontSize: 14, fontWeight: '500' },
  centerBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  centerCard: { backgroundColor: '#1C1C1E', borderRadius: 20, padding: 20, alignSelf: 'stretch' },
  tagButton: { alignSelf: 'flex-start', backgroundColor: '#2C2C2E', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 7, marginBottom: 8 },
  tagButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '500' },
  tagButtonPlaceholder: { color: '#8E8E93' },
  tagDoneBtn: { backgroundColor: '#0A84FF', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  tagDoneText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  tagChip: { backgroundColor: '#2C2C2E', borderRadius: 16, paddingHorizontal: 20, paddingVertical: 14, minWidth: 76, alignItems: 'center' },
  tagChipOn: { backgroundColor: '#0A84FF' },
  tagChipText: { color: '#8E8E93', fontSize: 16, fontWeight: '600' },
  tagChipTextOn: { color: '#FFFFFF' },
  tagHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  tagEditBtn: { color: '#0A84FF', fontSize: 15, fontWeight: '600' },
  tagAddRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  tagAddInput: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, color: '#FFFFFF', fontSize: 15 },
  tagAddBtn: { backgroundColor: '#30D158', borderRadius: 12, paddingHorizontal: 18, justifyContent: 'center' },
  tagAddBtnText: { color: '#000000', fontSize: 15, fontWeight: '700' },
  tagBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 4 },
  tagBadge: { color: '#5AB0FF', fontSize: 11, fontWeight: '600', backgroundColor: '#0A2A4A', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 2, overflow: 'hidden' },
  sessionNoteInput: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
    minHeight: 44,
    marginBottom: 16,
  },
  cancelBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#2C2C2E',
    marginRight: 8,
  },
  cancelBtnText: { color: '#FF453A', fontSize: 15, fontWeight: '600' },

  gymBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  gymSheet: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 32 },
  gymSheetTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', marginBottom: 12 },
  gymItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  gymItemText: { color: '#FFFFFF', fontSize: 16, flexShrink: 1 },
  gymCheck: { color: '#30D158', fontSize: 16, fontWeight: '700', marginLeft: 8 },
  gymEmpty: { color: '#48484A', fontSize: 14, paddingVertical: 12 },
  gymActionEdit: { color: '#8E8E93', fontSize: 14, fontWeight: '600', marginLeft: 14 },
  gymActionDelete: { color: '#FF453A', fontSize: 14, fontWeight: '600', marginLeft: 14 },
  gymEditInput: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, color: '#FFFFFF', fontSize: 16 },
  gymActionSave: { color: '#30D158', fontSize: 14, fontWeight: '700', marginLeft: 14 },
  gymActionCancel: { color: '#8E8E93', fontSize: 14, fontWeight: '600', marginLeft: 12 },
  gymAddRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 14 },
  gymAddInput: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, color: '#FFFFFF', fontSize: 15 },
  gymAddBtn: { backgroundColor: '#30D158', borderRadius: 10, paddingHorizontal: 18, paddingVertical: 11 },
  gymAddBtnText: { color: '#06210F', fontSize: 15, fontWeight: '800' },

  historyTitle: { color: '#8E8E93', fontSize: 13, fontWeight: '600', textTransform: 'uppercase', marginBottom: 12 },
  historyCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
  },
  historyCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  historyDate: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  historyDuration: { color: '#8E8E93', fontSize: 13 },
  historyExercises: { color: '#8E8E93', fontSize: 14, marginBottom: 4 },
  historyMeta: { color: '#48484A', fontSize: 12 },

  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1C1C1E',
  },
  detailHeaderTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' },
  detailDelete: { color: '#FF453A', fontSize: 16, fontWeight: '600', width: 60, textAlign: 'right' },
  setReadOnly: {
    flex: 1,
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 16,
    paddingVertical: 10,
    fontVariant: ['tabular-nums'],
  },

  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#1C1C1E',
  },
  sessionTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  sessionElapsed: { color: '#30D158', fontSize: 14, fontWeight: '600', marginTop: 2, fontVariant: ['tabular-nums'] },
  sessionDateSub: { color: '#8E8E93', fontSize: 13, marginTop: 3 },
  finishBtn: { backgroundColor: '#30D158', borderRadius: 12, paddingHorizontal: 20, paddingVertical: 8 },
  finishBtnText: { color: '#000000', fontSize: 15, fontWeight: '700' },

  // 상단 고정 바
  stickyBar: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingTop: 6, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#1C1C1E' },
  stickyElapsed: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7 },
  stickyDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#30D158' },
  stickyElapsedText: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', fontVariant: ['tabular-nums'] },
  stickyRest: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  stickyRestCenter: { flex: 1, alignItems: 'center' },
  stickyRestTime: { color: '#30D158', fontSize: 20, fontWeight: '800', fontVariant: ['tabular-nums'] },
  stickyRestLabel: { color: '#8E8E93', fontSize: 11, fontWeight: '600', marginTop: 1 },
  stickyAdj: { backgroundColor: '#1C1C1E', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 },
  stickyAdjText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700', fontVariant: ['tabular-nums'] },
  stickySkip: { backgroundColor: '#1C1C1E', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 },
  stickySkipText: { color: '#8E8E93', fontSize: 14, fontWeight: '800' },
  stickyFinish: { backgroundColor: '#30D158', borderRadius: 12, paddingHorizontal: 18, paddingVertical: 8 },
  stickyFinishText: { color: '#06210F', fontSize: 15, fontWeight: '800' },

  scrollContent: { padding: 16, paddingBottom: 60 },
  scrollContentRest: { paddingTop: 56, paddingBottom: 60 },
  scrollContentEditing: { paddingBottom: 300 },
  restDock: { position: 'absolute', left: 0, right: 0, bottom: 0 },
  restDockEditing: { bottom: 252 },

  emptyHint: { alignItems: 'center', paddingVertical: 40 },
  emptyHintText: { color: '#48484A', fontSize: 15 },

  exerciseCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  exerciseCardDragging: { opacity: 0.92, borderWidth: 1, borderColor: '#30D158', backgroundColor: '#23241F' },
  exerciseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  exerciseName: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  exerciseBrand: { color: '#8E8E93', fontSize: 13, marginTop: 2 },
  exVolume: { color: '#8E8E93', fontSize: 13, fontWeight: '600', marginTop: 4, fontVariant: ['tabular-nums'] },
  exNoteInput: {
    backgroundColor: '#23201A',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#E5C07B',
    fontSize: 13,
    marginBottom: 6,
    marginTop: 2,
  },
  exSessionNoteInput: {
    backgroundColor: '#2C2C2E',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#FFFFFF',
    fontSize: 13,
    marginBottom: 10,
  },
  ormBadge: {
    color: '#30D158',
    fontSize: 13,
    fontWeight: '600',
    backgroundColor: '#1A3D27',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  exerciseHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  exDeleteBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#2C2C2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exDeleteText: { color: '#8E8E93', fontSize: 14, fontWeight: '700' },
  exMenuBtn: {
    width: 34,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#2C2C2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exMenuText: { color: '#8E8E93', fontSize: 18, fontWeight: '700', marginTop: -4 },

  menuOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  menuSheet: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 12, paddingBottom: 32 },
  menuHeader: { color: '#8E8E93', fontSize: 13, fontWeight: '600', paddingHorizontal: 12, paddingTop: 4, paddingBottom: 8 },
  menuItem: { paddingVertical: 16, paddingHorizontal: 12 },
  menuItemText: { color: '#FFFFFF', fontSize: 17 },
  rmPickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingVertical: 8 },
  rmPickChip: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, backgroundColor: '#2C2C2E' },
  rmPickChipOn: { backgroundColor: '#30D158' },
  rmPickText: { color: '#8E8E93', fontSize: 15, fontWeight: '600' },
  rmPickTextOn: { color: '#000000' },
  menuCancel: { marginTop: 8, paddingVertical: 16, alignItems: 'center', backgroundColor: '#2C2C2E', borderRadius: 12 },
  menuCancelText: { color: '#FFFFFF', fontSize: 17, fontWeight: '600' },
  restSeg: { flexDirection: 'row', backgroundColor: '#2C2C2E', borderRadius: 10, padding: 4, marginHorizontal: 12, marginTop: 4 },
  restSegBtn: { flex: 1, paddingVertical: 9, borderRadius: 8, alignItems: 'center' },
  restSegBtnOn: { backgroundColor: '#30D158' },
  restSegText: { color: '#8E8E93', fontSize: 15, fontWeight: '600' },
  restSegTextOn: { color: '#0A1F12' },
  restReadout: { color: '#FFFFFF', fontSize: 44, fontWeight: '800', textAlign: 'center', marginTop: 14, fontVariant: ['tabular-nums'] },
  restAdjRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, marginTop: 4 },
  restAdjBtn: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: '#2C2C2E', alignItems: 'center' },
  restAdjText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', fontVariant: ['tabular-nums'] },

  setHeader: { flexDirection: 'row', marginBottom: 4 },
  setCol: { flex: 1, color: '#8E8E93', fontSize: 12, textAlign: 'center' },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    borderRadius: 8,
    backgroundColor: '#2C2C2E',
  },
  setRowDone: { backgroundColor: '#15351F' },
  setRowWarmup: { backgroundColor: '#2A2620' },
  setNum: { flex: 0.5, alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  setNumText: {
    color: '#AEAEB2', textAlign: 'center', fontSize: 13, fontWeight: '600',
    minWidth: 26, paddingVertical: 3,
    borderWidth: 1, borderColor: '#48484A', borderRadius: 6, overflow: 'hidden',
  },
  setTypeBadge: {
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    minWidth: 22,
    borderWidth: 1.5,
    borderRadius: 6,
    paddingVertical: 1,
    overflow: 'hidden',
  },
  setInput: {
    width: '100%',
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    paddingVertical: 10,
    fontVariant: ['tabular-nums'],
  },
  stepRow: { flexDirection: 'row', alignItems: 'center' },
  stepBtn: {
    width: 30, height: 34, borderRadius: 8, backgroundColor: '#3A3A3C',
    alignItems: 'center', justifyContent: 'center',
  },
  stepText: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  setInputStep: {
    flex: 1,
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    paddingVertical: 10,
    fontVariant: ['tabular-nums'],
  },
  fieldBtn: {
    paddingVertical: 9,
    marginHorizontal: 2,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  fieldActive: { borderColor: '#30D158', backgroundColor: '#14331F' },
  fieldText: { color: '#FFFFFF', fontSize: 18, fontWeight: '600', fontVariant: ['tabular-nums'] },
  fieldPlaceholder: { color: '#48484A', fontWeight: '500' },
  prevHint: {
    color: '#6E6E73',
    fontSize: 10,
    textAlign: 'center',
    marginTop: -6,
    marginBottom: 4,
    fontVariant: ['tabular-nums'],
  },
  checkBtn: { flex: 0.6, alignItems: 'center', justifyContent: 'center', paddingVertical: 8 },
  checkCircle: {
    width: 27, height: 27, borderRadius: 14,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1.5, borderColor: '#48484A',
  },
  checkCircleDone: { backgroundColor: '#30D158', borderColor: '#30D158' },
  checkCirclePR: { backgroundColor: '#FFD60A', borderColor: '#FFD60A' },
  checkMark: { color: '#0A1F12', fontSize: 15, fontWeight: '900' },
  checkTrophy: { fontSize: 14 },

  dragHandle: {
    width: 34,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#2C2C2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dragHandleText: { color: '#8E8E93', fontSize: 18, fontWeight: '700' },

  detailNoteChip: {
    backgroundColor: '#2C2C2E',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
  },
  detailNoteChipText: { color: '#E5E5EA', fontSize: 13 },

  kbAccessory: {
    backgroundColor: '#1C1C1E',
    borderTopWidth: 1,
    borderTopColor: '#2C2C2E',
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'flex-end',
  },
  kbAccessoryText: { color: '#30D158', fontSize: 16, fontWeight: '700' },

  templateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#1C1C1E',
    borderRadius: 14,
    padding: 16,
    marginBottom: 8,
  },
  templateName: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  templateMeta: { color: '#8E8E93', fontSize: 12, marginTop: 3 },
  templateStartBtn: { backgroundColor: '#30D158', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 8 },
  templateStartText: { color: '#000000', fontSize: 14, fontWeight: '700' },
  templateDelBtn: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#2C2C2E', alignItems: 'center', justifyContent: 'center' },
  templateDelText: { color: '#8E8E93', fontSize: 13, fontWeight: '700' },
  detailSaveBtn: {
    backgroundColor: '#30D158',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  detailSaveText: { color: '#000000', fontSize: 16, fontWeight: '700' },
  detailTemplateBtn: {
    borderWidth: 1,
    borderColor: '#FF9F0A',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  detailTemplateText: { color: '#FF9F0A', fontSize: 15, fontWeight: '600' },
  timeBadge: { color: '#0A84FF', fontSize: 12, fontWeight: '700', marginBottom: 6 },
  memoBtnRow: { flexDirection: 'row', marginBottom: 8 },
  memoChip: { alignSelf: 'flex-start', backgroundColor: '#2C2C2E', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, maxWidth: '100%' },
  memoChipOn: { backgroundColor: '#14331F', borderWidth: 1, borderColor: '#30D158' },
  memoChipText: { color: '#E5C07B', fontSize: 13, fontWeight: '600' },
  memoChipPlaceholder: { color: '#8E8E93', fontWeight: '500' },
  setActionsRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  warmupBtn: {
    backgroundColor: '#2A2620',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  warmupBtnText: { color: '#FF9F0A', fontSize: 14, fontWeight: '600' },
  summaryOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', padding: 28 },
  summaryCard: { backgroundColor: '#1C1C1E', borderRadius: 24, padding: 28 },
  summaryTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '700', textAlign: 'center', marginBottom: 20 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  summaryItem: { width: '50%', alignItems: 'center', paddingVertical: 12 },
  summaryValue: { color: '#30D158', fontSize: 26, fontWeight: '700', fontVariant: ['tabular-nums'] },
  summaryLabel: { color: '#8E8E93', fontSize: 13, marginTop: 4 },
  summaryBtn: { backgroundColor: '#30D158', borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 16 },
  summaryBtnText: { color: '#000000', fontSize: 16, fontWeight: '700' },
  warmupSheet: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 32 },
  warmupTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  warmupHint: { color: '#8E8E93', fontSize: 13, marginTop: 4, marginBottom: 14 },
  warmupRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  warmupInput: {
    backgroundColor: '#2C2C2E', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10,
    color: '#FFFFFF', fontSize: 16, minWidth: 70, textAlign: 'center', fontVariant: ['tabular-nums'],
  },
  warmupUnit: { color: '#8E8E93', fontSize: 15 },
  warmupStepper: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#2C2C2E', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 4 },
  warmupValue: { color: '#FFFFFF', fontSize: 16, fontWeight: '600', fontVariant: ['tabular-nums'] },
  warmupBaseRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 10, marginBottom: 6 },
  warmupBaseLabel: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
  warmupApplied: { color: '#30D158', fontSize: 13, fontWeight: '600', minWidth: 52, textAlign: 'right', fontVariant: ['tabular-nums'] },
  warmupDel: { marginLeft: 'auto', width: 28, height: 28, borderRadius: 14, backgroundColor: '#2C2C2E', alignItems: 'center', justifyContent: 'center' },
  warmupDelText: { color: '#8E8E93', fontSize: 13, fontWeight: '700' },
  warmupAddRow: { paddingVertical: 10, alignItems: 'center' },
  warmupAddRowText: { color: '#FF9F0A', fontSize: 14, fontWeight: '600' },
  warmupActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  warmupCancel: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  warmupCancelText: { color: '#8E8E93', fontSize: 16, fontWeight: '600' },
  warmupApply: { flex: 1, backgroundColor: '#FF9F0A', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  warmupApplyText: { color: '#000000', fontSize: 16, fontWeight: '700' },
  historyBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  repeatBtn: {
    backgroundColor: '#1A3D27',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  repeatBtnText: { color: '#30D158', fontSize: 13, fontWeight: '600' },

  deleteAction: {
    backgroundColor: '#FF453A',
    justifyContent: 'center',
    alignItems: 'center',
    width: 72,
    borderRadius: 8,
    marginBottom: 4,
  },
  deleteActionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  addSetBtn: {
    borderWidth: 1,
    borderColor: '#3A3A3C',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  addSetText: { color: '#8E8E93', fontSize: 14 },

  addExerciseBtn: {
    borderWidth: 2,
    borderColor: '#30D158',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginTop: 4,
  },
  addExerciseBtnText: { color: '#30D158', fontSize: 17, fontWeight: '700' },

  // 운동 선택 모달
  modalSafe: { flex: 1, backgroundColor: '#000000' },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1C1C1E',
  },
  modalBack: { color: '#30D158', fontSize: 16, width: 60 },
  modalTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  modalContent: { padding: 16 },
  searchInput: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 12,
  },
  trackingRow: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 8 },
  trackingBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, backgroundColor: '#2C2C2E', alignItems: 'center' },
  trackingBtnOn: { backgroundColor: '#0A84FF' },
  trackingText: { color: '#8E8E93', fontSize: 14, fontWeight: '600' },
  trackingTextOn: { color: '#FFFFFF' },
  quickAddTitle: { color: '#8E8E93', fontSize: 13, fontWeight: '600', marginBottom: 10, textTransform: 'uppercase' },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    backgroundColor: '#1A3D27',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 9,
    maxWidth: '48%',
  },
  chipOn: { backgroundColor: '#30D158' },
  chipText: { color: '#30D158', fontSize: 14, fontWeight: '600' },
  chipTextOn: { color: '#0A1F12' },
  chipBrand: { color: '#6E9E7E', fontSize: 11, marginTop: 1 },
  muscleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  muscleBtn: {
    width: '46%',
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  muscleBtnText: { color: '#FFFFFF', fontSize: 18, fontWeight: '600' },
  choiceBtn: {
    backgroundColor: '#1C1C1E',
    borderRadius: 14,
    padding: 18,
    marginBottom: 10,
  },
  choiceBtnOutline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#30D158',
  },
  choiceText: { color: '#FFFFFF', fontSize: 17 },
  exItem: {
    backgroundColor: '#1C1C1E',
    borderRadius: 14,
    padding: 18,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exItemOn: { backgroundColor: '#16301F', borderWidth: 1, borderColor: '#30D158' },
  exItemMain: { flex: 1, paddingRight: 12 },
  favStar: { fontSize: 22 },
  exName: { color: '#FFFFFF', fontSize: 16 },
  exBrand: { color: '#8E8E93', fontSize: 13, marginTop: 2 },
  exArrow: { color: '#8E8E93', fontSize: 24 },
  exCheck: { color: '#30D158', fontWeight: '800' },
  addBar: {
    position: 'absolute',
    left: 0, right: 0, bottom: 0,
    padding: 16,
    paddingBottom: 28,
    backgroundColor: 'rgba(0,0,0,0.85)',
    borderTopWidth: 1,
    borderTopColor: '#2C2C2E',
  },
  addBarBtn: {
    backgroundColor: '#30D158',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  addBarBtnText: { color: '#0A1F12', fontSize: 17, fontWeight: '800' },
  customBtn: {
    borderWidth: 1,
    borderColor: '#30D158',
    borderRadius: 14,
    padding: 18,
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 20,
  },
  customBtnText: { color: '#30D158', fontSize: 16 },

  customFormLabel: { color: '#8E8E93', fontSize: 13, marginBottom: 8, textTransform: 'uppercase' },
  customFormSub: { color: '#48484A', fontSize: 13, marginBottom: 24, marginTop: 8 },
  input: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 4,
  },
  saveBtn: {
    backgroundColor: '#30D158',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
  },
  saveBtnText: { color: '#000000', fontSize: 17, fontWeight: '700' },
});
